export type Template = typeof template;

export const template = {
  counters: { u_column: 4, u_row: 3, u_content_html: 1 },
  body: {
    id: "Rw1AtxxSRa",
    rows: [
      {
        id: "1Yr8yHzZE2",
        cells: [1],
        columns: [
          {
            id: "wIsfHFaKIM",
            contents: [],
            values: {
              backgroundColor: "",
              padding: "0px",
              border: {},
              borderRadius: "0px",
              _meta: { htmlID: "u_column_3", htmlClassNames: "u_column" },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "",
          columnsBackgroundColor: "",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          padding: "0px",
          anchor: "",
          _meta: { htmlID: "u_row_2", htmlClassNames: "u_row" },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },
      {
        id: "temMkhpsmF",
        cells: [1],
        columns: [
          {
            id: "8cgRZGnaaf",
            contents: [
              {
                id: "huaWLKt_ro",
                type: "html",
                values: {
                  html: '<div style="font-family: Helvetica,Arial,sans-serif;overflow:auto;">\n    <div style="margin:10px auto;padding:0px 0;width:900px;max-width:100%;background:#fff;border-radius:2px;">\n        <div style="border-bottom:1px solid #eee">\n            <a href="[[${PREFERENCES_LINK}]]"              style="font-size:1.4em;color: #00466a;text-decoration:none;font-weight:700">Preferences</a>\n        </div>\n        <div style="float:right;padding:8px 0;color:#aaa;font-size:0.8em;line-height:1;font-weight:300">\n            <p> Adria Business & Technology © 2024</p>\n            <p>Casanearshore,Casablanca, Maroc</p>\n        </div>\n    </div>\n</div>',
                  displayCondition: null,
                  containerPadding: "10px",
                  anchor: "",
                  _meta: {
                    htmlID: "u_content_html_1",
                    htmlClassNames: "u_content_html",
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                },
              },
            ],
            values: {
              backgroundColor: "",
              padding: "0px",
              border: {},
              borderRadius: "0px",
              _meta: { htmlID: "u_column_1", htmlClassNames: "u_column" },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: "",
          columnsBackgroundColor: "",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
            customPosition: ["50%", "50%"],
          },
          padding: "0px",
          anchor: "",
          hideDesktop: false,
          _meta: { htmlID: "u_row_1", htmlClassNames: "u_row" },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },
    ],
    headers: [],
    footers: [],
    values: {
      popupPosition: "center",
      popupWidth: "600px",
      popupHeight: "auto",
      borderRadius: "10px",
      contentAlign: "center",
      contentVerticalAlign: "center",
      contentWidth: "500px",
      fontFamily: { label: "Arial", value: "arial,helvetica,sans-serif" },
      textColor: "#000000",
      popupBackgroundColor: "#FFFFFF",
      popupBackgroundImage: {
        url: "",
        fullWidth: true,
        repeat: "no-repeat",
        size: "cover",
        position: "center",
      },
      popupOverlay_backgroundColor: "rgba(0, 0, 0, 0.1)",
      popupCloseButton_position: "top-right",
      popupCloseButton_backgroundColor: "#DDDDDD",
      popupCloseButton_iconColor: "#000000",
      popupCloseButton_borderRadius: "0px",
      popupCloseButton_margin: "0px",
      popupCloseButton_action: {
        name: "close_popup",
        attrs: {
          onClick:
            "document.querySelector('.u-popup-container').style.display = 'none';",
        },
      },
      backgroundColor: "#F7F8F9",
      preheaderText: "",
      linkStyle: {
        body: true,
        linkColor: "#0000ee",
        linkHoverColor: "#0000ee",
        linkUnderline: true,
        linkHoverUnderline: true,
      },
      backgroundImage: {
        url: "",
        fullWidth: true,
        repeat: "no-repeat",
        size: "custom",
        position: "center",
      },
      _meta: { htmlID: "u_body", htmlClassNames: "u_body" },
    },
  },
  schemaVersion: 16,
};
